### PR TITLE
Proposed fix for #386

### PR DESCRIPTION
**Pull request by Sigma88**
this might be the solution to issue #386

### CODE REVIEW

**Comment by Sigma88** [comment]
I had to change the code to use

```value > 30 ? 30 : value > 1 ? value : 1;```

because apparently KSP mods still have some of those values as Double

valid alternatives could be:


```
        [ParserTarget("octaves")]
        public NumericParser<Int32> Octaves
        {
            get { return (Int32)Mod.octaves; }
            set { Mod.octaves = Mathf.Clamp(value, 1, 30); }
        }
```

or adding an extension for clamping doubles like this:

```
        public static Double Clamp(this NumericParser<Double> value, Double min, Double max)
        {
            if (value > max)
                return max;

            if (value > min)
                return value;

            return min;
        }
```

which would then result in the code for the octaves to look like this:

```
        [ParserTarget("octaves")]
        public NumericParser<Double> Octaves
        {
            get { return Mod.octaves; }
            set { Mod.octaves = value.Clamp(1, 30); }
        }
```

**Comment by StollD** [comment]
I haven't checked the KSP API yet, but if the datatypes of the parsers don't match the ones of the values behind them, the parsers should be adjusted. If they are doubles, we should just use `Math.Clamp` instead of `Mathf.Clamp`.

**Comment by Sigma88** [comment]
ok

I will update the code, however I don't think that it will be enough

**Comment by Sigma88** [comment]
I made the changes, however I think this will still result in an error if the "octaves" parameter is missing in the cfg

**Comment by Sigma88** [comment]
nice!

I'll delete the branch because we already have too many of them 🤣

**Pull request merged**
