### PR TITLE
Sigma 1

### PR DESCRIPTION
**Pull request by Sigma88**
added some stuff to enhance compatibility

### CODE REVIEW

**Comment by Sigma88** [comment]
these changes are simple enough that I think there shouldn't be any problems in adding them

@StollD  maybe take a look to make sure I didn't do something stupid :D

**Comment by StollD** [comment]
I don't know if I like that currentBody stuff to be honest...

If you really want it, please add currentBody to BaseLoader, make it default to generatedBody, and change all the loaders to include a third constructor that accepts a PSystemBody. (which then sets currentBody)

**Comment by Sigma88** [comment]
gotcha

**Comment by Sigma88** [comment]
can I change the generatedBody to be non-static?

**Comment by Sigma88** [comment]
I think this should do the trick

        public class BaseLoader
        {
            public PSystemBody currentBody = null;

            // Singleton of the currently edited body
            public PSystemBody generatedBody
            {
                get
                {
                    if (currentBody != null)
                        return currentBody;
                    else
                        return Loader.currentBody.generatedBody;
                }
            }
        }

**Comment by Sigma88** [comment]
alternatively we could use


            public PSystemBody currentBody { internal get; set; }

instead of 

            public PSystemBody currentBody = null;

**Comment by StollD** [comment]
I like your first suggestion, but I would suggest to make both, generatedBody and currentBody protected instead of public

**Pull request merged**
